name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Maven
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Maven requires Node.js, so we set up Node.js here

      - name: Build with Maven
        run: mvn clean install

      - name: Prepare Docker image files
        run: |
          mkdir docker
          cp build/libs/*.jar docker/app.jar
          cp Dockerfile docker/

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/item-service docker

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Dockerhub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/item-service
